# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180314_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='value',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
