# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-16 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180314_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category',
            new_name='name',
        ),
    ]
