# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180316_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
