# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import farmzone.catalog.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180319_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_orig',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='farmzone-dev-public'), upload_to=farmzone.catalog.models.upload_product_orig_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='img_thumb',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='farmzone-dev-public'), upload_to=farmzone.catalog.models.upload_product_thumb_image_path),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='img_orig',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='farmzone-dev-public'), upload_to=farmzone.catalog.models.upload_sub_product_orig_image_path),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='img_thumb',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='farmzone-dev-public'), upload_to=farmzone.catalog.models.upload_sub_product_thumb_image_path),
        ),
    ]
