branch-defaults:
  master:
    environment: farmzone-dev
environment-defaults:
  farmzone-dev:
    branch: null
    repository: null
global:
  application_name: farmzone
  default_ec2_keyname: farmzone-dev
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Python 3.4 running
    on 64bit Amazon Linux/2.4.2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application

