# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_auto_20180327_0539'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='seller_code',
        ),
        migrations.AddField(
            model_name='support',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.Seller'),
        ),
    ]
