# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180416_1445'),
        ('support', '0008_auto_20180503_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='seller_sub_product',
        ),
        migrations.AddField(
            model_name='support',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderDetail'),
        ),
    ]
