# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_preferredseller_is_primary'),
        ('support', '0010_supportcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='product_serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.Seller'),
        ),
    ]
