version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/python:3.6.1
        environment:
        - DATABASE_URL=mysql://root@127.0.0.1:3306/circle_test
      - image: circleci/mysql:5.7
    branches:
      only:
        - stage
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - requirements-{{ .Branch }}-{{ checksum "requirements/local.txt" }}-{{ checksum "requirements/base.txt" }}

      - run:
          name: Download requirements.txt
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/local.txt
      - save_cache:
          name: requirements-cache
          key: requirements-{{ .Branch }}-{{ checksum "requirements/local.txt" }}-{{ checksum "requirements/base.txt" }}
          paths:
            - "venv"
      - run:
          name: Running Tests with Coverage
          command: |
            . venv/bin/activate
            python manage.py test --verbosity=0 || echo "=======Completed====="
            coverage html -i
      - store_artifacts:
          path: htmlcov
      - run:
          name: Download EB_CLI
          command: sudo pip install awsebcli
      - run:
          name: Create .elasticbeanstalk configuration
          command: mkdir .elasticbeanstalk && mv .circleci/elasticbeanstalk_config.yml .elasticbeanstalk/config.yml
      - deploy:
          name: Deploying Changes
          command: |
            if [[ ${CIRCLE_BRANCH} == "master" || ${CIRCLE_BRANCH} == "s3-storage-branch" ]]; then
              echo "Deploying changes to farmzone-dev"
              eb deploy farmzone-dev
            elif [[ ${CIRCLE_BRANCH} == "stage" ]]; then
              echo "Deploying changes to farmzone-stage"
              eb deploy farmzone-stage
            elif [[ ${CIRCLE_BRANCH} == "production"  ]]; then
              echo "Deploying changes to farmzone-prod"
              eb deploy farmzone-prod
            fi
            rm -r .elasticbeanstalk/

