# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_sellerowners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerOwners',
            new_name='SellerOwner',
        ),
    ]
