# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-16 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_auto_20180316_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
