# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180319_2346'),
        ('sellers', '0007_sellersubproduct_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellersubproduct',
            unique_together=set([('seller', 'sub_product')]),
        ),
    ]
