# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-27 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_auto_20180322_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sellersubproduct',
            name='sub_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_sub_products', to='catalog.SubProduct'),
        ),
    ]
