# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_auto_20180327_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredseller',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
