# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-24 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notifications', '0005_applicationid'),
        ('sellers', '0014_userproduct_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fcm_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_notifications.GCMDevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Device',
                'verbose_name_plural': 'Seller Devices',
                'db_table': 'seller_device',
            },
        ),
    ]
