# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180330_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
