# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cart_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='seller_sub_product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'COMPLETED'), ('CART', 'CART')], default='New', max_length=30),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
