# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180416_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
