# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderdetail_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED'), ('DISPATCHED', 'DISPATCHED'), ('CART', 'CART'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=30),
        ),
    ]
