# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20180504_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailProductIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_identifier', models.CharField(max_length=100)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderDetail')),
            ],
            options={
                'db_table': 'order_detail_product_identifier',
                'verbose_name': 'Order Detail Product Identifier',
                'verbose_name_plural': 'Order Product Identifiers',
            },
        ),
    ]
