# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderdetailproductidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailproductidentifier',
            name='product_identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
