# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
