# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import farmzone.core.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180314_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_orig',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='farmzone-dev-public'), upload_to=farmzone.core.models.upload_orig_image_path),
        ),
        migrations.AddField(
            model_name='user',
            name='img_thumb',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='farmzone-dev-public'), upload_to=farmzone.core.models.upload_thumb_image_path),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
