# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180412_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('source', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=10)),
                ('other', jsonfield.fields.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User App Info',
                'verbose_name_plural': 'User App Info',
                'db_table': 'user_app_info',
            },
        ),
    ]
