# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userappinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappinfo',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
