# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180416_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_welcome_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
